const data: {
	[key: string]: [string | string[], number];
} = {
	'Andaman and Nicobar Islands': ['AN', 35],
	'Andhra Pradesh': ['AP', 28],
	'Arunachal Pradesh': ['AR', 12],
	Assam: ['AS', 18],
	Bihar: ['BR', 10],
	Chandigarh: ['CH', 4],
	Chhattisgarh: ['CT', 22],
	'Dadra and Nagar Haveli and Daman and Diu': [['DN', 'DD'], 26],
	Delhi: ['DL', 7],
	Goa: ['GA', 30],
	Gujarat: ['GJ', 24],
	Haryana: ['HR', 6],
	'Himachal Pradesh': ['HP', 2],
	'Jammu and Kashmir': ['JK', 1],
	Jharkhand: ['JH', 20],
	Karnataka: ['KA', 29],
	Kerala: ['KL', 32],
	Ladakh: ['LA', 37],
	Lakshadweep: ['LD', 31],
	'Madhya Pradesh': ['MP', 23],
	Maharashtra: ['MH', 27],
	Manipur: ['MN', 14],
	Meghalaya: ['ML', 17],
	Mizoram: ['MZ', 15],
	Nagaland: ['NL', 13],
	Odisha: ['OR', 21],
	Puducherry: ['PY', 34],
	Punjab: ['PB', 3],
	Rajasthan: ['RJ', 8],
	Sikkim: ['SK', 11],
	'Tamil Nadu': ['TN', 33],
	Telangana: ['TG', 36],
	Tripura: ['TR', 16],
	Uttarakhand: ['UT', 5],
	'Uttar Pradesh': ['UP', 9],
	'West Bengal': ['WB', 19],
};
export default data;
